Config = {
    --LANGUAGE/LICENSE
    Language = "fr", -- (fr, es, en, de, pl, tr)
    Key = "T74NJ-siEp7-BhnNx-gfFji", -- Key you get when you buy
    ServerName = "AlmaRP", -- Please set it

    --OPTION DETECTION
    BanSystem = true,
    KickMessage = "You have been detected !",
    BanMessage = "You were banned for life for using cheating software !",

    AlertDiscord = true,
    WebhookDiscord = "https://canary.discord.com/api/webhooks/882174667178246154/jw5rHSGNkhhdE3oagcu_sSKJ8MFX_LTBPl7r4M1EuZ4Obw0NH2JgemQYdd18gKovRxS6",

    DetectionNumberEntity = 10,
    RatelimitDetection = 50,
    RatelimitReset = 10,

    --TECHNIQUE OPTION WORLD-AC
    RemoveAllEntityWhenPlayersLeave = true,
    BlacklistEntity = true,
    MassEntityProtection = true, --Warning entity like NPC
    BlacklistTriggerProtection = true,
    RatelimitTriggerProtection = true,

    BlacklistTrigger = {
        "Blacklist:Trigger",
    },

    RatelimitTrigger = {
        "Ratelimit:Trigger",
    },
    --LIST CAN BE CONFIG
    EntityBlacklist = {
        --VEHICLE
        "akula",
        "annihilator",
        "buzzard",
        "buzzard2",
        "cargobob",
        "cargobob2",
        "cargobob3",
        "cargobob4",
        "frogger",
        "frogger2",
        "hunter",
        "savage",
        "skylift",
        "valkyrie",
        "valkyrie2",
        "annihilator2",
        "apc",
        "barrage",
        "chernobog",
        "halftrack",
        "khanjali",
        "rhino",
        "scarab",
        "scarab2",
        "scarab3",
        "thruster",
        "trailersmall2",
        "dominator6",
        "dukes2",
        "ruiner3",
        "brutus",
        "brutus2",
        "brutus3",
        "bruiser",
        "bruiser2",
        "bruiser3",
        "dune2",
        "insurgent",
        "insurgent2",
        "insurgent3",
        "avenger",
        "avenger2",
        "besra",
        "bombushka",
        "cargoplane",
        "hydra",
        "jet",
        "lazer",
        "mogul",
        "molotok",
        "strikeforce",
        "starling",
        "rogue",
        "pyro",
        "titan",
        "tula",
        "volatol",
        "alkonost",
        "limo2",
        "wastelander",
        "zr380",
        "zr3802",
        "zr3803",
        "vigilante",
        "voltic2",
        "armytanker",
        "armytrailer",
        "armytrailer2",
        "baletrailer",
        "boattrailer",
        "cablecar",
        "docktrailer",
        "freighttrailer",
        "graintrailer",
        "proptrailer",
        "raketrailer",
        "tr2",
        "tr3",
        "tr4",
        "trflat",
        "tvtrailer",
        "tanker",
        "tanker2",
        "trailerlarge",
        "trailerlogs",
        "trailersmall",
        "trailers",
        "trailers2",
        "trailers3",
        "trailers4",
        "freight",
        "freightcar",
        "freightcont1",
        "freightcont2",
        "freightgrain",
        "metrotrain",
        "tankercar",
        "tractor",
        "slamtruck",
        "boxville5",
        "dinghy5",
        "kosatka",
        "patrolboat",
        "cerberus",
        "cerberus2",
        "cerberus3",
        "phantom2",
        "akula",
        "annihilator",
        "buzzard",
        "buzzard2",
        "skylift",
        "revolter",
        "valkyrie2",
        "airbus",
        "hunter",
        "armytanker",
        "armytrailer",
        "armytrailer2",
        "baletrailer",
        "boattrailer",
        "cablecar",
        "docktrailer",
        "freighttrailer",
        "graintrailer",
        "proptrailer",
        "raketrailer",
        "tr2",
        "tr3",
        "tr4",
        "trflat",
        "tanker",
        "tanker2",
        "trailerlarge",
        "trailersmall",
        'RHINO',
        'SAVAGE',
        'HUNTER',
        'ANNIHILATOR',
        'VALKYRIE',
        'HYDRA',
        'APC',
        'Lazer',
        'oppressor',
        'mogul',
        'Khanjali',
        'volatol',
        'chernobog',
        'avenger',
        'stromberg',
        'nightshark',
        'besra',
        'babushka ',
        'starling',
        'insurgent',
        'cargobob',
        'cargobob2',
        'cargobob3',
        'cargobob4',
        'deluxo',
        'menacer',
        'scramjet',
        'oppressor2',
        'viseris',
        'thruster',
        'ardent',
        'dune3',
        'tampa3',
        'nokota',
        'strikeforce',
        'bombushka',
        'molotok',
        'pyro',
        'ruiner2',
        'limo2',
        'technical',
        'technical2',
        'technical3',
        'jb700w',
        'blazer5',
        'insurgent3',
        'boxville5',
        'bruiser',
        'bruiser2',
        'bruiser3',
        'brutus',
        'brutus2',
        'brutus3',
        'cerberus',
        'cerberus2',
        'cerberus3',
        'dominator4',
        'dominator5',
        'dominator6',
        'impaler2',
        'impaler3',
        'impaler4',
        'imperator',
        'imperator2',
        'imperator3',
        'issi4',
        'issi5',
        'issi6',
        'monster',
        'monster3',
        'monster4',
        'monster5',
        'scarab',
        'scarab2',
        'scarab3',
        'slamvan4',
        'slamvan5',
        'slamvan6',
        'zr380',
        'zr3802',
        'zr3803',
        'alphaz1',
        'avenger2',
        'blimp',
        'blimp2',
        'blimp3',
        'cargoplane',
        'cuban800',
        'dodo',
        'duster',
        'howard',
        'jet',
        'luxor',
        'luxor2',
        'mammatus',
        'microlight',
        'miljet',
        'nimbus',
        'rogue',
        'seabreeze',
        'shamal',
        'stunt',
        'titan',
        'tula',
        'velum',
        'velum2',
        'vestra',
        "s_m_y_swat_01",
        "a_m_o_acult_01",
        "ig_wade",
        "s_m_y_hwaycop_01",
        "A_M_Y_ACult_01",
        's_m_m_movalien_01',
        's_m_m_movallien_01',
        'u_m_y_babyd',
        'CS_Orleans',
        'A_M_Y_ACult_01',
        'S_M_M_MovSpace_01',
        'U_M_Y_Zombie_01',
        's_m_y_blackops_01',
        'a_f_y_topless_01',
        'a_c_boar',
        'a_c_cat_01',
        'a_c_chickenhawk',
        'a_c_chimp',
        's_f_y_hooker_03',
        'a_c_cormorant',
        'a_c_cow',
        'a_c_crow',
        'a_c_dolphin',
        'a_c_fish',
        's_f_y_hooker_01',
        'a_c_hen',
        'a_c_humpback',
        'a_c_husky',
        'a_c_killerwhale',
        'a_c_mtlion',
        'a_c_pigeon',
        'a_c_poodle',
        'a_c_pug',
        'a_c_rabbit_01',
        'a_c_rat',
        'a_c_rhesus',
        'a_c_sharkhammer',
        'a_c_sharktiger',
        'a_c_shepherd',
        'a_c_stingray',
        'a_c_westy',
        'cs_orleans',
        'ig_orleans',
        'mp_f_freemode_01',
    },
    
    PropsWhitelist = {
        'prop_ballistic_shield',
    },
}