--[[
    If I have made any mistakes please feel free to correct it and send it to me so I can update it. 
]]--

Traduction = {
    ["fr"] = {
        WebhookError = "Vous n'avez pas mis de webhook valide !",
        InfoPlayers = "Information Joueur",
        PlayerID = "Identifiant du joueur",
        PlayerName = "Nom du joueur",
        SanctionString = "Sanction",
        SanctionApplicated = "Sanction Appliquer",
        DetectionReceive = "Detection recu",
        ErrorCode = "Désolé, nous avons eu un problème avec l'authentification, essayez à nouveau dans quelques secondes.",
        ErrorCode2 = "Peut-être que vous n'avez pas de licence ou que vous n'avez pas indiqué l'adresse IP de votre serveur dans notre système d'authentification.",
        ErrorCode3 = "Si le problème persiste, veuillez nous contacter ici : discord.gg/37tD84WC44.",
        StartMessage = "Démarrage de ",
        StartMessage2 = " réussi",
        Loading = "Chargement.",
        Started = "Démarrage réussi.",
    },
    ["en"] = {
        WebhookError = "You have not set a valid webhook!",
        InfoPlayers = "Player Information",
        PlayerID = "Player ID",
        PlayerName = "Player name",
        SanctionString = "Sanction",
        SanctionApplicated = "Sanction Apply",
        DetectionReceive = "Detection received",
        ErrorCode = "Sorry, we had a problem with authentication, try again in a few seconds.",
        ErrorCode2 = "Maybe you don't have a license or you haven't entered your server's IP address in our authentication system.",
        ErrorCode3 = "If the problem persists, please contact us here: discord.gg/37tD84WC44.",
        StartMessage = "start of ",
        StartMessage2 = " succeeded",
        Loading = "Loading.",
        Started = "Successful start.",
    },
    ["es"] = {
        WebhookError = "No ha configurado un webhook válido !",
        InfoPlayers = "Información del jugador",
        PlayerID = "ID de jugador",
        PlayerName = "Nombre del jugador",
        SanctionString = "Sanción",
        SanctionApplicated = "Aplicar sanción",
        DetectionReceive = "Detección recibida",
        ErrorCode = "Lo sentimos, tuvimos un problema con la autenticación. Vuelve a intentarlo en unos segundos..",
        ErrorCode2 = "Tal vez no tenga una licencia o no haya ingresado la dirección IP de su servidor en nuestro sistema de autenticación.",
        ErrorCode3 = "Si el problema persiste, contáctenos aquí: discord.gg/37tD84WC44.",
        StartMessage = "Inicio de ",
        StartMessage2 = " triunfado",
        Loading = "Cargando.",
        Started = "Inicio exitoso.",
    },
    ["de"] = {
        WebhookError = "Sie haben keinen gültigen Webhook festgelegt !",
        InfoPlayers = "Spielerinformationen",
        PlayerID = "Spieler-ID",
        PlayerName = "Spielername",
        SanctionString = "Sanktion",
        SanctionApplicated = "Sanktion beantragen",
        DetectionReceive = "Erkennung empfangen",
        ErrorCode = "Entschuldigung, wir hatten ein Problem mit der Authentifizierung, versuchen Sie es in ein paar Sekunden noch einmal.",
        ErrorCode2 = "Vielleicht haben Sie keine Lizenz oder Sie haben die IP-Adresse Ihres Servers nicht in unserem Authentifizierungssystem eingegeben.",
        ErrorCode3 = "Wenn das Problem weiterhin besteht, kontaktieren Sie uns bitte hier: discord.gg/37tD84WC44.",
        StartMessage = "Start von ",
        StartMessage2 = " gelungen",
        Loading = "Wird geladen.",
        Started = "Erfolgreicher Start.",
    },
    ["pl"] = {
        WebhookError = "Nie ustawiłeś prawidłowego webhooka !",
        InfoPlayers = "Informacje o graczu",
        PlayerID = "Identyfikator gracza",
        PlayerName = "Nazwa gracza",
        SanctionString = "Sankcja",
        SanctionApplicated = "Nałożenie sankcji",
        DetectionReceive = "Otrzymano wykrycie",
        ErrorCode = "Przepraszamy, wystąpił problem z uwierzytelnianiem, spróbuj ponownie za kilka sekund.",
        ErrorCode2 = "Być może nie masz licencji lub nie wpisałeś adresu IP swojego serwera w naszym systemie uwierzytelniania.",
        ErrorCode3 = "Jeśli problem będzie się powtarzał, skontaktuj się z nami tutaj: discord.gg/37tD84WC44.",
        StartMessage = "Początek ",
        StartMessage2 = " udało się",
        Loading = "Ładowanie.",
        Started = "Udany start.",
    },
    ["tr"] = {
        WebhookError = "Geçerli bir web kancası ayarlamadınız !",
        InfoPlayers = "Oyuncu Bilgileri",
        PlayerID = "oyuncu kimliği",
        PlayerName = "Oyuncu ismi",
        SanctionString = "yaptırım",
        SanctionApplicated = "Yaptırım Uygulanması",
        DetectionReceive = "Algılama alındı",
        ErrorCode = "Maalesef kimlik doğrulamayla ilgili bir sorun yaşadık, birkaç saniye sonra tekrar deneyin.",
        ErrorCode2 = "Belki bir lisansınız yoktur veya sunucunuzun IP adresini doğrulama sistemimize girmemişsinizdir.",
        ErrorCode3 = "Sorun devam ederse, lütfen bizimle buradan iletişime geçin: discord.gg/37tD84WC44.",
        StartMessage = "Başlamak ",
        StartMessage2 = " başarılı",
        Loading = "Yükleniyor.",
        Started = "Başarılı başlangıç.",
    },
}